version: '3.8'

services:
  app:
    build: .
    image: interview:v1.0
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: interview
      DB_USER: user
      DB_PASSWORD: p@ssword
      KUBERNETES: "no"
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: p@ssword
      POSTGRES_DB: interview
      TABLE_NAME: query_history 
    volumes:
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    ports:
      - "5432:5432"

