apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.app.name }}-db-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.db.env.postgresUser | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.db.env.postgresPassword | b64enc }}
  POSTGRES_DB: {{ .Values.db.env.postgresDb | b64enc }}
  TABLE_NAME: {{ .Values.db.env.table | b64enc }}

