apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app.name }}-app
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{.Values.app.name }}-app
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app.name }}-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/name: {{.Values.app.name }}-db
    app.kubernetes.io/instance: {{ .Release.Name }}
     

