name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Install dependencies
      run: go mod download

    - name: Lint with golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.42.1

    - name: Run tests
      run: go run main.go

  build-docker-image:
    runs-on: ubuntu-latest
    needs: test-and-lint

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: zilgopy/interview:${{ github.sha }}

  package-helm-chart:
    runs-on: ubuntu-latest
    needs: build-docker-image

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v1

    - name: Lint Helm chart
      run: |
        helm lint helm-interview

    - name: Package Helm chart
      run: |
        helm package helm-interview

